#!/bin/sh
#
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

action="$1"
if [ "$2" = "in-favour" ]; then
  # Treat conflict remove as an upgrade.
  action="upgrade"
fi
# Don't clean-up just for an upgrade.`
if [ "$action" = "upgrade" ] ; then
  exit 0
fi

if [ "xconsumer" != "xplugin" ]; then
  # Remove icons from the system icons
  XDG_ICON_RESOURCE="`which xdg-icon-resource 2> /dev/null`"
  if [ ! -x "$XDG_ICON_RESOURCE" ]; then
    echo "Error: Could not find xdg-icon-resource" >&2
    exit 1
  fi
  for icon in "/opt/google/earth/free/product_logo_"*.png; do
    size="${icon##*/product_logo_}"
    "$XDG_ICON_RESOURCE" uninstall --size "${size%.png}" "google-earth"
  done

  # Remove the entry from the system menu
  XDG_DESKTOP_MENU="`which xdg-desktop-menu 2> /dev/null`"
  UPDATE_MENUS="`which update-menus 2> /dev/null`"
  if [ ! -x "$XDG_DESKTOP_MENU" ]; then
    echo "Error: Could not find xdg-desktop-menu" >&2
    exit 1
  fi
  "$XDG_DESKTOP_MENU" uninstall /opt/google/earth/free/google-earth.desktop

  if [ -x "$UPDATE_MENUS" ]; then
    update-menus
  fi
else
  # Remove the plugin from Mozilla plugin directory.
  echo "Removing Google Earth plugin from /usr/lib/mozilla/plugins."
  rm -rf /usr/lib/mozilla/plugins/libnpgeplugin.so
fi
